### ISSUE TITLE
Self-debiasing yields unexpected results

### ISSUE THREAD

**Issue by neoyipeng2018** [timoschick/dino#9]
Hi Timo, thanks for the cool work you've done around PLMs! ❤️

Been trying out the package, albeit on a smaller GPT model on a different language, and the results of using the debiasing feature is quite unexpected. My use case is similar to the IMDB review generation, where we generate sentences of opposite polarity, and I provide instructions/examples prompt like in GPT-3's paper. 

To use the self-debiasing feature, I indicated that positive sentences should be different from negative sentences. However, the results of the generation are skewed: only one label has good sentences, and the other label has gibberish. My guess is that my examples had similar sentence structure, with just the sentiment words flipped, so the model was trying to avoid generating similar sentences.

For generating sentence with different polarity, wondering what are the best practices, or if I was doing anything wrong?

**Comment by timoschick** [comment]
Hi @neoyipeng2018, thank you for your interest in our work 😊
A couple of thoughts: 
- We've been doing some experiments with smaller LMs on other languages, and this didn't work particularly well in many cases. Which language/model have you been working with?
- Could you share your task specification with me (similar to [this one for IMDB](https://github.com/timoschick/dino/blob/main/task_specs/imdb-reviews.json)) so that I can check whether something looks wrong there?
- Did you try whether it works well for both labels if you do *not* use self-debiasing?

**Comment by neoyipeng2018** [comment]
Hi @timoschick, i see, thanks for sharing - i was working on chinese language, trying out a few of the models here: https://huggingface.co/models?language=zh&pipeline_tag=text-generation&sort=downloads.

Sure, it goes something like this, but in chinese:

LABEL_1
Generate 3 positive news headlines:
Headline 1: "Profits went up this quarter"
Headline 2: "We managed to acquire company XYZ at a low cost"
Headline 3: " 
COUNTER_LABEL=LABEL_2

LABEL_2
Generate 3 negative news headlines:
Headline 1: "Profits went down this quarter"
Headline 2: "We did not manage to acquire company XYZ"
Headline 3: "
COUNTER_LABEL=LABEL_1

Yea, when I set lambda to 0, the outputted sentences were both alright. I was hoping to use the self-debiasing feature though, because otherwise I could probably just use huggingface's pipeline directly?

**Comment by timoschick** [comment]
> I was hoping to use the self-debiasing feature though, because otherwise I could probably just use huggingface's pipeline directly?

Yes, absolutely. This was just meant to be a sanity check to trace the root of your problem. Unfortunately, I don't really have a good intuition as to where your problem comes from as I haven't worked with Chinese LMs before. You may try DINO with some English language model just to see whether everything works as intended there, that may help if there are any issues with the implementation itself or the environment you're using to run it. Apart from that, I'm afraid I don't have any useful suggestions at the moment.
